package Model;

public enum ConnectType {
    ASSOCIATION_LINE_START,
    ASSOCIATION_LINE_END,
    GENERALIZATION_LINE_START,
    GENERALIZATION_LINE_END,
    COMPOSITION_LINE_START,
    COMPOSITION_LINE_END,
    NONE;
}
